<?php
// This file generated by Propel 1.7.1 convert-conf target
return array (
  'BaseMigrations' => 'Orm/om/BaseMigrations.php',
  'BaseMigrationsPeer' => 'Orm/om/BaseMigrationsPeer.php',
  'BaseMigrationsQuery' => 'Orm/om/BaseMigrationsQuery.php',
  'Migrations' => 'Orm/Migrations.php',
  'MigrationsPeer' => 'Orm/MigrationsPeer.php',
  'MigrationsQuery' => 'Orm/MigrationsQuery.php',
  'MigrationsTableMap' => 'Orm/map/MigrationsTableMap.php',
);