<?php
// This file generated by Propel 1.7.1 convert-conf target
// from XML runtime conf file /Users/zanasmon/Sites/vettersoftware/vs/intern/intern_logbook/src/config/propel/config/runtime-conf.xml
$conf = array (
  'datasources' =>
  array (
    'orm' =>
    array (
      'adapter' => 'mysql',
      'connection' =>
      array (
        'dsn' => '',
        'user' => '',
        'password' => '',
      ),
    ),
    'default' => 'orm',
  ),
  'generator_version' => '1.7.1',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-orm-conf.php');
return $conf;